.TH "AsteroidRotation" 3 "Thu Oct 28 2021" "CrossPlatform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AsteroidRotation
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBrotationSpeed\fP = 0\&.1f"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CrossPlatform from the source code\&.
