.TH "playership" 3 "Thu Oct 28 2021" "CrossPlatform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
playership
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBBullet\fP"
.br
.ti -1c
.RI "ParticleSystem \fBexplosion\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CrossPlatform from the source code\&.
