.TH "score" 3 "Thu Oct 28 2021" "CrossPlatform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
score
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddPoints\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBscoreText\fP"
.br
.ti -1c
.RI "int \fBscores\fP = 0"
.br
.ti -1c
.RI "int \fBpoints\fP = 1"
.br
.ti -1c
.RI "int \fBhighscore\fP = 1"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBscore\fP \fBinstance\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CrossPlatform from the source code\&.
